package thread;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static thread.ThreadGUI.Base_Path;
import static thread.ThreadGUI.T_Dog;
import static thread.ThreadGUI.T_Human;
import static thread.ThreadGUI.T_Polic;
import static thread.ThreadGUI.image;
import static thread.ThreadGUI.image_Bandit;
import static thread.ThreadGUI.image_Dog;
import static thread.ThreadGUI.image_polic;
import static thread.ThreadGUI.picture;
import static thread.ThreadGUI.statusBandit;
import static thread.ThreadGUI.statusDog;
import static thread.ThreadGUI.statusHuman;
import static thread.ThreadGUI.statusPolic;
import static thread.ThreadGUI.status_B;
import static thread.ThreadGUI.status_D;
import static thread.ThreadGUI.status_H;
import static thread.ThreadGUI.status_P;
import static thread.ThreadGUI.i;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import static thread.ThreadGUI.status;
import static thread.ThreadGUI.time;
import static java.lang.Thread.sleep;
import static thread.ThreadGUI.date;

public class ThreadGUI extends javax.swing.JFrame implements MouseListener, ActionListener {

    public static String picture = null;
    public static String statusHuman = "WakeUp";
    public static String statusDog = "Sleep";
    public static String statusPolic = "Stanby";
    public static String statusBandit = "Sleep";
    public static Boolean status = false;
    public static Human T_Human;
    public static Dog T_Dog;
    public static Polic T_Polic;
    public static Thif T_Bandit;
    public static String Base_Path = "C:\\Users\\Administrator\\Desktop\\System\\Thread\\res\\";
    public static Clock clock = new Clock();
    public static int i;

    public ThreadGUI() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        status_H = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        image_Dog = new javax.swing.JLabel();
        status_D = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        image_polic = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_bandit = new javax.swing.JButton();
        image_Bandit = new javax.swing.JLabel();
        status_B = new javax.swing.JLabel();
        status_P = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        time = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));
        jPanel1.setForeground(new java.awt.Color(51, 51, 0));

        image.setIcon(new javax.swing.ImageIcon(Base_Path+"\\wakeUp.png"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addContainerGap())
        );

        status_H.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        status_H.setText(statusHuman);
        status_H.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));
        jPanel2.setForeground(new java.awt.Color(51, 51, 0));

        image_Dog.setIcon(new javax.swing.ImageIcon(Base_Path+"\\dog_sleep.png"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image_Dog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image_Dog, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addContainerGap())
        );

        status_D.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        status_D.setText(statusDog);
        status_D.setToolTipText("");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));
        jPanel3.setForeground(new java.awt.Color(51, 51, 0));

        image_polic.setIcon(new javax.swing.ImageIcon(Base_Path+"\\stanby.png"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image_polic, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image_polic, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));
        jPanel4.setForeground(new java.awt.Color(51, 51, 0));

        btn_bandit.setText("Rob");
        btn_bandit.addMouseListener(this);
        btn_bandit.addActionListener(this);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_bandit))
                    .addComponent(image_Bandit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image_Bandit, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_bandit))
        );

        image_Bandit.setIcon(new javax.swing.ImageIcon(Base_Path +"bandit_sleep.png"));

        status_B.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        status_B.setText(statusBandit);
        status_B.setToolTipText("");

        status_P.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        status_P.setText(statusPolic);
        status_P.setToolTipText("");

        btnStart.setText("Start");
        btnStart.addMouseListener(this);
        btnStart.addActionListener(this);

        time.setFont(new java.awt.Font("Old English Text MT", 1, 18)); // NOI18N
        time.setText("00:00");

        jLabel1.setFont(new java.awt.Font("TH Charm of AU", 1, 24)); // NOI18N
        jLabel1.setText("Day");

        date.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(status_P, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status_H, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(status_D, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status_B, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(date))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(time)
                .addGap(173, 173, 173)
                .addComponent(btnStart)
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStart)
                            .addComponent(time)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(status_D, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(status_H, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(status_P, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(status_B, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == btn_bandit) {
            ThreadGUI.this.btn_banditActionPerformed(evt);
        }
        else if (evt.getSource() == btnStart) {
            ThreadGUI.this.btnStartActionPerformed(evt);
        }
    }

    public void mouseClicked(java.awt.event.MouseEvent evt) {
        if (evt.getSource() == btn_bandit) {
            ThreadGUI.this.btn_banditMouseClicked(evt);
        }
        else if (evt.getSource() == btnStart) {
            ThreadGUI.this.btnStartMouseClicked(evt);
        }
    }

    public void mouseEntered(java.awt.event.MouseEvent evt) {
    }

    public void mouseExited(java.awt.event.MouseEvent evt) {
    }

    public void mousePressed(java.awt.event.MouseEvent evt) {
    }

    public void mouseReleased(java.awt.event.MouseEvent evt) {
    }// </editor-fold>//GEN-END:initComponents

    private void btn_banditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_banditMouseClicked

        if (statusBandit == "Sleep") { //WakeUp , Sleep
            try {
                T_Bandit.interrupt();
                status = true;
                clock.stop();
            } catch (Exception e) {
            }

        } else {
            JOptionPane.showMessageDialog(null, "โจรหลับอยู่", "Bandit Dialog", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btn_banditMouseClicked

    private void btn_banditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_banditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_banditActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed

    }//GEN-LAST:event_btnStartActionPerformed

    private void btnStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseClicked

        clock.start();
        status = false;

    }//GEN-LAST:event_btnStartMouseClicked

    public static void main(String args[]) {
        T_Human = new Human();
        T_Bandit = new Thif();
        T_Dog = new Dog();
        T_Polic = new Polic();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new ThreadGUI().setVisible(true);

            }
        });

        if (!T_Polic.isAlive()) {
            T_Polic.start();
        }
        if (!T_Human.isAlive()) {
            T_Human.start();
        }
        if (!T_Dog.isAlive()) {
            T_Dog.start();
            T_Dog.setPriority(4);
        }
        if (!T_Bandit.isAlive()) {
            T_Bandit.start();
            T_Bandit.setPriority(3);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnStart;
    public static javax.swing.JButton btn_bandit;
    public static javax.swing.JLabel date;
    public static javax.swing.JLabel image;
    public static javax.swing.JLabel image_Bandit;
    public static javax.swing.JLabel image_Dog;
    public static javax.swing.JLabel image_polic;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    public static javax.swing.JPanel jPanel3;
    public static javax.swing.JPanel jPanel4;
    public static javax.swing.JLabel status_B;
    public static javax.swing.JLabel status_D;
    public static javax.swing.JLabel status_H;
    public static javax.swing.JLabel status_P;
    public static javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}

class Human extends Thread {

    public void run() {

        while (Thread.currentThread().isAlive() && !status) {

            try {

                System.out.println(i);
                statusHuman = "WakeUp";
                picture = "wakeup";
                System.out.println(statusHuman);
                status_H = new JLabel();
                image = new JLabel();
                status_H.setText(statusHuman);
                sleep(16000);
                System.out.println(Thread.currentThread().getState());
                System.out.println(i);
                statusHuman = "Sleep";
                picture = "sleep";
                System.out.println(statusHuman);
                status_H.setText(statusHuman);
                image.setIcon(new ImageIcon(Base_Path + "sleep.png"));
                sleep(8000);
            } catch (InterruptedException ex) {
                statusHuman = "WakeUp";
                picture = "wakeup";
                image.setIcon(new ImageIcon(Base_Path + "wakeup.png"));
                status_H.setText(statusHuman);
                T_Polic.interrupt();
            }

        }

    }
}

class Dog extends Thread {

    public void run() {

        while (Thread.currentThread().isAlive() && !status) {
            try {

                statusDog = "Sleep";
                picture = "dog_sleep";
                status_D = new JLabel();
                image_Dog = new JLabel();
                status_D.setText(statusDog);
                image_Dog.setIcon(new ImageIcon(Base_Path + "dog_sleep.png"));
                sleep(16000);

                statusDog = "WakeUp";
                picture = "dog_wakeUp";
                status_D.setText(statusDog);
//            System.out.println("DOG" + picture);
                image_Dog.setIcon(new ImageIcon(Base_Path + "dog_wakeUp.png"));

            } catch (InterruptedException ex) {
                T_Human.interrupt();
                statusDog = "WakeUp";
                picture = "dog_wakeUp";
                status_D.setText(statusDog);
                image_Dog.setIcon(new javax.swing.ImageIcon(Base_Path + "dog_wakeUp.png"));
            }
        }
        Thread.currentThread().stop();
    }
}

class Polic extends Thread {

    public void run() {

        try {
            status_P = new JLabel();
            image_polic = new JLabel();
            synchronized (T_Polic) {
                T_Polic.wait();
            }
        } catch (InterruptedException ire) {
            statusPolic = "Work";
            picture = "work";
            status_P.setText(statusPolic);
//            System.out.println(statusPolic);
            image_polic.setIcon(new javax.swing.ImageIcon(Base_Path + "work.png"));
            JOptionPane.showMessageDialog(null, "ตำรวจจับ", "Polic Dialog", JOptionPane.INFORMATION_MESSAGE);
        }
    }
}

class Thif extends Thread {

    public void run() {

        while (Thread.currentThread().isAlive() && !status) {
            try {

                statusBandit = "Sleep";
                picture = "dog_sleep";
                status_B = new JLabel();
                image_Bandit = new JLabel();
                status_B.setText(statusDog);
                image_Bandit.setIcon(new ImageIcon(Base_Path + "dog_sleep.png"));
                sleep(16000);

                statusBandit = "WakeUp";
                picture = "dog_wakeUp";
                status_B.setText(statusDog);
//            System.out.println("DOG" + picture);
                image_Bandit.setIcon(new ImageIcon(Base_Path + "bandit_wakeUp.png"));

            } catch (InterruptedException ex) {
                System.out.println("xxxx");
                T_Dog.interrupt();
                statusBandit = "WakeUp";
                picture = "bandit_wakeUp";
                status_B.setText(statusBandit);
                image_Bandit.setIcon(new javax.swing.ImageIcon(Base_Path + "bandit_wakeUp.png"));
                image_polic.setIcon(new ImageIcon(Base_Path + "work.png"));
            }
        }

    }

}

class Clock extends Thread {

    int day = 0;

    public void run() {

        for (i = 0; i < 25; i++) {
            time.setText(i + ":00");
            try {
                sleep(1000);
                if (i == 24) {
                    i = 0;
                    this.interrupt();
                }
            } catch (InterruptedException ex) {
                try {
                    sleep(1000);
                } catch (InterruptedException ex1) {
                    Logger.getLogger(Clock.class.getName()).log(Level.SEVERE, null, ex1);
                }
                day++;
                date.setText(day + "");

            }
        }

    }

}
